---
title: "Week9-collab-doc"
format: html
editor: visual
---

Load Libraries

```{r}
library(tidyverse) #for data wrangling 
library(lterdatasampler) #for data
library(ggeffects) #for model
library(here) #for file path

```

Reading in data:

```{r}
data(pie_crab)
```

I will visualize the data!!

```{r}
ggplot(aes(x = latitude, y = size), data = pie_crab) + #create ggplot
  geom_point(color = "orange") + #scatterplot with orange points
  labs(x = "Latitude", y = "Size") + #update axis labels
  theme_minimal() #update theme to not have grid lines
```

writing a model here:

```{r}
crab_model <- lm(size ~ latitude, # formula: response ~ predicor
                 data = pie_crab) # data frame

par(mfrow = c(2,2)) #display plots 2x2 grid
plot(crab_model) # plot diagnostics
```

Run the model and interpret

```{r}
summary(crab_model) #look at model output
```
Summarize our results: 

slope: 0.49
y-intercept: -3.6 +/- 1.27

For every 1 increase in latitude, we expect to see a 0.49 increase in crab size +/- 0/034mm.

Model statistics: F(1,390) = 208.5, p < 0.001, alpha = 0.05, R^2^ = 0.35




